### ISSUE TITLE
Removing package website from README which now links to a porn website

### ISSUE THREAD

**Issue by IndrajeetPatil** [Rapporter/rapport#109]
The `README` links to the following website for package docs: http://rapport-package.info/. But this domain now belongs toa  website with pornographic content. 

Not sure if you are aware of this and I thought it would be good to bring it to your attention in case you were not. So better to remove that link from `README` asap.

**Comment by daroczig** [comment]
Oh my .. thanks for letting me about this :facepalm: :scream: 
I'm trying to remove that reference ASAP.

**Comment by daroczig** [comment]
Package docs and REAME updated, CNAME deleted in GH pages, GH URL changed to github.io, but I will keep this ticket open to make sure cleaning up all other references and submit a new pkg version to CRAN.

**Comment by IndrajeetPatil** [comment]
Fantastic! 

Thank you for fixing this so quickly. :)

**Comment by daroczig** [comment]
![image](https://user-images.githubusercontent.com/495736/114322530-0381db00-9b21-11eb-9eaf-73e3f2880c4d.png)
